version: '3.8'
services:
  config-server:
    image: plchavez98/tds-microservice-config-server:latest
    container_name: config-server
    ports:
      - 8888:8888
    environment:
      CONFIG_SERVER_GIT_URI: https://github.com/pedro-chavezcastro/tds-configuration
      CONFIG_SERVER_GIT_BRANCH: main
      CONFIG_SERVER_GIT_USERNAME: pedro-chavezcastro
      CONFIG_SERVER_GIT_PASSWORD: Daniela_Aragon#0223
    restart: always
    networks:
      - tds-cloud
  eureka-server:
    image: plchavez98/tds-microservice-eureka-server:latest
    container_name: eureka-serve
    ports:
      - 8761:8761
    restart: always
    networks:
      - tds-cloud     
  tds-microservice-products:
    image: plchavez98/tds-microservice-products:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    restart: always
    depends_on:
      - config-server
      - eureka-server
    networks:
      - tds-cloud
  tds-microservice-users:
    image: plchavez98/tds-microservice-users:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    restart: always
    depends_on:
      - config-server
      - eureka-server
    networks:
      - tds-cloud
  oauth2-server:
    image: plchavez98/tds-microservice-oauth2-server:latest
    container_name: oauth2-serve
    ports:
      - 9100:9100
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - tds-cloud
    depends_on:
      - config-server
      - eureka-server
      - tds-microservice-users
  zuul-server:
    image: plchavez98/tds-microservice-zuul-server:latest
    ports:
      - 8090:8090
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - tds-cloud
    depends_on:
      - config-server
      - eureka-server
      - tds-microservice-products
      - tds-microservice-users
      - oauth2-server      
  mysql8:
    image: mysql:8
    container_name: mysql8
    ports:
      - 3306:3306
    restart: always
    networks:
      - tds-cloud
    environment:
      MYSQL_DATABASE: db_springboot_cloud
      MYSQL_ROOT_PASSWORD: sasa      
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - /var/lib/rabbitmq:/var/lib/rabbitmq
    networks:
      - tds-cloud
  tds-microservice-zipkin-server:
    image: plchavez98/tds-microservice-zipkinserver:lates
    container_name: tds-microservice-zipkin-server
    ports:
      - 9411:9411
    restart: always
    networks:
      - tds-cloud
    depends_on:
      - mysql8
      - rabbitmq
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
      STORAGE_TYPE: mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
      MYSQL_HOST: mysql8
networks:
  tds-cloud: