version: '3.8'
services:
  eureka-server:
    image: 'plchavez98/tds-microservice-eureka-server:${EUREKA_SERVER_VERSION}'
    ports:
      - 8761:8761
    restart: always
    networks:
      - tds-microservices-dev
  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER_FILE: /run/secrets/rabbitmq_username
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    networks:
      - tds-microservices-dev
  tds-microservice-zipkin-server:
    image: 'plchavez98/tds-microservice-zipkinserver:${ZIPKIN_SERVER_VERSION}'
    ports:
      - 9411:9411
    restart: always
    networks:
      - tds-microservices-dev
    depends_on:
      - rabbitmq
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
      STORAGE_TYPE: mysql
      MYSQL_DB: zipkin-dev
      MYSQL_USER: zipkin-dev
      MYSQL_PASS: zipkin-dev
      MYSQL_HOST: mysql8      
  tds-microservice-products:
    image: 'plchavez98/tds-microservice-products:${MICRO_PRODUCTS_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
    networks:
      - tds-microservices-dev
    secrets:
       - db-url
       - db-name
       - db-username
       - db-password
       - rabbitmq-username
       - rabbitmq-password 
networks:
  tds-microservices-dev:
    name: tds-microservices-dev
    external: true
secrets:
  rabbitmq_username:
    external: true
  rabbitmq_password:
    external: true    
  db-url:
    external: true    
  db-name:
    external: true
  db-username:
    external: true
  db-password:
    external: true
  rabbitmq-username:
    external: true
  rabbitmq-password:
    external: true