version: '3.8'
services:
  eureka-server:
    image: 'plchavez98/tds-microservice-eureka-server:${EUREKA_SERVER_VERSION}'
    ports:
      - 8761:8761
    restart: always
    networks:
      - tds-microservices-dev
  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tds-microservices-dev
  tds-microservice-zipkin-server:
    image: 'plchavez98/tds-microservice-zipkinserver:${ZIPKIN_SERVER_VERSION}'
    ports:
      - 9411:9411
    restart: always
    networks:
      - tds-microservices-dev
    depends_on:
      - rabbitmq
    environment:
      RABBIT_ADDRESSES: rabbitmq:5672
      STORAGE_TYPE: mysql
      MYSQL_DB: zipkin-dev
      MYSQL_USER: zipkin-dev
      MYSQL_PASS: zipkin-dev
      MYSQL_HOST: mysql8      
  tds-microservice-products:
    image: 'plchavez98/tds-microservice-products:${MICRO_PRODUCTS_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      TDS_DB_CONFIG_URL: /run/secrets/database_url_secret
      TDS_DB_CONFIG_NAME: /run/secrets/database_name_secret
      TDS_DB_CONFIG_USERNAME: /run/secrets/database_username_secret
      TDS_DB_CONFIG_PASSWORD: /run/secrets/database_password_secret
      TDS_RABBIT_CONFIG_USERNAME: /run/secrets/rabbit_username_secret
      TDS_RABBIT_CONFIG_PASSWORD: /run/secrets/rabbit_password_secret
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
    networks:
      - tds-microservices-dev
    secrets:
       - database_url_secret
       - database_name_secret
       - database_username_secret
       - database_password_secret
       - rabbit_username_secret
       - rabbit_password_secret
  tds-microservice-suppliers:
    image: 'plchavez98/tds-microservice-suppliers:${MICRO_SUPPLIERS_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      SPRING_CLOUD_CONFIG_URI: 'http://config-server:8888'
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
      - tds-microservice-products
    networks:
      - tds-microservices-dev
  tds-microservice-sales:
    image: 'plchavez98/tds-microservice-sales:${MICRO_SALES_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: 'dev'
      SPRING_CLOUD_CONFIG_URI: 'http://config-server:8888'
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
      - tds-microservice-products
    networks:
      - tds-microservices-dev      
  tds-microservice-orders:
    image: 'plchavez98/tds-microservice-orders:${MICRO_ORDERS_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
      - tds-microservice-products
    networks:
      - tds-microservices-dev
  tds-microservice-users:
    image: 'plchavez98/tds-microservice-users:${MICRO_USERS_VERSION}'
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    restart: always
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
    networks:
      - tds-microservices-dev
  oauth2-server:
    image: 'plchavez98/tds-microservice-oauth2-server:${OAUTH_SERVER_VERSION}'
    ports:
      - 9100:9100
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - tds-microservices-dev
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
      - tds-microservice-users
  zuul-server:
    image: 'plchavez98/tds-microservice-zuul-server:${ZUUL_SERVER_VERSION}'
    ports:
      - 8090:8090
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - tds-microservices-dev
    depends_on:
      - eureka-server
      - tds-microservice-zipkin-server
      - tds-microservice-products
      - tds-microservice-suppliers
      - tds-microservice-sales
      - tds-microservice-orders
      - tds-microservice-users
      - oauth2-server
networks:
  tds-microservices-dev:
    name: tds-microservices-dev
    external: true
secrets:
  database_url_secret:
    external: true    
  database_name_secret:
    external: true
  database_username_secret:
    external: true
  database_password_secret:
    external: true
  rabbit_username_secret:
    external: true
  rabbit_password_secret:
    external: true    